# Support Etiqueta by using the links below
# Etiqeuta and the public datasets shared in this repo are developed and maintained by Dr. Semih Yagli.
# GitHub Sponsors: https://github.com/sponsors/semihyagli
# Buy Me a Coffee: https://buymeacoffee.com/semihyagli

github: semihyagli
buy_me_a_coffee: semihyagli

# Your support helps me in continuing to develop many other labeled opensource datasets. 
# Thank you very much!